# Generated by Django 2.0 on 2020-08-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserField',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], max_length=20),
        ),
    ]
