# Generated by Django 2.0 on 2020-08-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxApp', '0002_auto_20200825_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserField',
            field=models.CharField(blank=True, choices=[('student', 'student'), ('teacher', 'teacher')], max_length=20),
        ),
    ]
