# Generated by Django 2.0 on 2020-08-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjaxApp', '0003_auto_20200826_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserField',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], max_length=20),
        ),
    ]
